version: '2'

services:
  cassandra:
    image: cassandra:latest
    hostname: cassandradb
    container_name: cassandradb
    restart: always
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7199:7199"
      - "7000:7000"
      - "7001:7001"